[package]
name = "ltr390-embedded-hal"
version = "0.1.0"
authors = ["EncinitasMechanic <84678085+EncinitasMechanic@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1.0.0"